### ISSUE TITLE
Error: unknown CSR `mhcr' (arch/riscv/cpu/c9xx/cpu.c:128)

### ISSUE THREAD

**Issue by colemickens** [revyos/thead-u-boot#10]
Does u-boot require building with a fork of gnu build tools? Will this requirement be removed sometime?

**Comment by RevySR** [comment]
https://github.com/revyos/thead-u-boot/pull/11

**Comment by RevySR** [comment]
https://github.com/revyos/thead-u-boot/commit/a75631c2e32c8b4d51cb9806f90f6c6bfcf5834d
