### ISSUE TITLE
android boot support broken?

### ISSUE THREAD

**Issue by yujincheng08** [revyos/thead-u-boot#35]
I tried to build with `light_lpi4a_android_defconfig` (see https://github.com/yujincheng08/thead-u-boot/actions/runs/8408969655)

But when I use `fastboot flash ram .\u-boot-with-spl-lpi4a-android.bin && fastboot reboot`, it stucks

**Comment by RevySR** [comment]
The main branch of this project has not tested android related functionality.

Please use the original sdk branch
https://github.com/revyos/thead-u-boot/tree/thead-sdk
